# Generated by Django 4.2.1 on 2023-05-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comerciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('fecha_incorporacion', models.DateField()),
                ('comision', models.FloatField()),
            ],
            options={
                'db_table': 'comerciales',
                'ordering': ['fecha_incorporacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('npasajeros', models.PositiveSmallIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('caballos', models.FloatField()),
                ('color', models.CharField(max_length=100)),
                ('cencubicos', models.PositiveIntegerField()),
                ('idcomercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.comerciales')),
            ],
            options={
                'db_table': 'vehiculos',
                'ordering': ['caballos'],
            },
        ),
    ]
